### ISSUE TITLE
Publishing the extension on OpenVSX

### ISSUE THREAD

**Issue by luzzif** [huff-language/vscode-huff#19]
Being a VSCodium user it would be great to have the extension available on OpenVSX too. Would that be possible?

**Comment by cheethas** [comment]
Hey there! I'm extremely sorry that this has gotten buried in my inbox, I've just started the process in getting the extension published over there too, hopefully it will be up and running shortly!

**Comment by cheethas** [comment]
Hi, 
I've just been granted publishing permissions and have published the extension to:
https://open-vsx.org/extension/huff-language/huff-language

Good luck have fun!

**Comment by cheethas** [comment]
@luzzif Let me know how it goes!
